name: 全量A股扫描
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python stock_scan.py
      - run: |
          git config --global user.name auto
          git config --global user.email auto@github.com
          git add stock_result.csv
          git commit -m "update" || echo "ok"
          git push
